version: '1'

networks:
  webapp:
    driver: bridge

services:
   nginx:
     container_name: nginx_container_2
     image: nginx
     ports:
       - "80:80"
     volumes:
       - type: bind
         source: ./docker/vhost.conf
         target: /etc/nginx/conf.d/default.conf
       - ./:/var/www/project
       - /var/www/project/node_modules
       - /var/www/project/vendor
       - ./docker/logs:/var/logs/nginx:rw
     links:
       - php
     depends_on:
       - php
       - db
     networks:
       - webapp

   php:
     container_name: php_container_2
     build:
       context: .
       dockerfile: ./Dockerfile
     depends_on:
       - db
     volumes:
       - ./:/var/www/project
       - /var/www/project/node_modules
       - /var/www/project/vendor
       - /.env
     networks:
       - webapp

   db:
     container_name: db_container_2
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: unless-stopped
     tty: true
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: mostsecurepassword
       MYSQL_DATABASE: dev
       SERVICE_TAGS: dev
       SERVICE_NAME: mysql
     networks:
       - webapp
     volumes:
       - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
